import { Separator } from "@/components/ui/separator"
import { AppSidebar } from "@/components/app-sidebar"
import { AppSidebarProvider } from "@/components/app-sidebar-provider"
import { SidebarInset, SidebarTrigger } from "@/components/ui/sidebar"
import { ThemeProvider } from "@/components/theme-provider"
import { ThemeToggle } from "@/components/theme-toggle"
import { DynamicBreadcrumb } from "@/components/navigation/dynamic-breadcrumb"
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <AppSidebarProvider>
            <AppSidebar />
            <SidebarInset>
              <header
                className="flex h-16 shrink-0 items-center justify-between gap-2 px-4 transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-12">
                <div className="flex items-center gap-2">
                  <SidebarTrigger className="-ml-1" />
                  <Separator orientation="vertical" className="mr-2 data-[orientation=vertical]:h-4" />
                  <DynamicBreadcrumb />
                </div>
                <ThemeToggle />
              </header>
              <main className="flex min-w-0 flex-1 flex-col gap-4 p-4 pt-0">
                {children}
              </main>
            </SidebarInset>
          </AppSidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
